language: python
script:
- pytest
env:
  global:
    secure: E72ZjUA4yqRrRn8KvL/jIQY2oQaOjmcjw72pI7+9l3pVmm2ztIUofp6VIDIPrkRW4UWk82SoLTFOSHBbuH7LBb1qTxH1tFrLmOv/te5RBr9I8NFoZ0AEgSHwL157rlw0hPEUtLgmx1v6vAcVKC1pMbcrD/klPkeH9IVdbnLr8+iX3/gAxZFZdvlCMkCJM3jjLFrKhR/56qeZjmP8Qq72ftNeJpVLk+0LXhliAsmBCwv/o59IvjBigDx/9bXlNAbUrQ1uZvO3NpFg6xWrF89u7zEztPuP9ho4dJG+okt2Ch36A1e30e3uU9IjRBf3OyhSc0f9QhW43oX0Rh0rYXuOhnh/7WBrWFkxKdnbgMXy57kfsPa+XHjfPLzYrRrpku4Xive7LYOO51Mj1ZLWIX3N32gYaAz4Y93hrtg3eQrlTAYyeTgIdSht48dRic1ggwcKdNWsQoTvrJGN2tjdtRPkTE0pQWB2+CYqdyxdmWRy0qxlxD4GyDObp9UIeKgQfv7ysxEIhsSh07iPLofX7kfGxmwxpvMZfhywQwjiPBeoY+QaSEOntiYJbKYPD71u3RvmqfZu+R9ZRdfjcnTZqIGK5F9cVw/tnfFBk2V0mK+TgzN4qb0FCey4kGXpk2bnf7S6QF37oFqKLYbVQuhq/DZp/tsYy9ytOXbK3Zg4lcJtH6Y=
